# Generated by Django 2.0.4 on 2018-04-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=4000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=4000)),
                ('current', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dobie.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('facebook_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=400)),
                ('access_token', models.CharField(max_length=400)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_change', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='responser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dobie.Users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dobie.Users'),
        ),
    ]
