# Generated by Django 2.0.4 on 2018-04-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dist',
            field=models.FloatField(default=0.0),
        ),
    ]
