# Generated by Django 2.0.4 on 2018-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.CharField(default='TBD', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
